import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Search, ShoppingBag, Menu, X, Plus, Minus, MessageCircle, Truck, ShieldCheck, Sparkles, ChevronLeft, ChevronRight } from 'lucide-react';
import logo from './assets/Logo.png';
import ProductGallery from './ProductGallery';
import ProductPage from './ProductPage';
import { supabase } from './lib/supabase';
import { getCartLines, getCartSummary, makeCartKey } from './data/cart';

const BASE = import.meta.env.BASE_URL;
function money(value){return Number(value??0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function uniqueImages(values){return [...new Set(values.filter(Boolean))];}
function normalizeProduct(product){const variants=(product.product_variants??[]).filter(v=>v.active).sort((a,b)=>a.sort_order-b.sort_order).map(v=>{const gallery=[...(v.product_variant_images??[])].sort((a,b)=>a.sort_order-b.sort_order);const primary=gallery.find(i=>i.is_primary)?.image_url||v.image_url||gallery[0]?.image_url||null;return{id:v.id,color:v.color,printPattern:v.print_pattern,image:primary,images:uniqueImages([primary,...gallery.map(i=>i.image_url),v.image_url]),sizes:[...(v.product_variant_stock??[])].sort((a,b)=>a.sort_order-b.sort_order).map(s=>({id:s.id,label:s.size,stock:s.stock}))};});return{id:product.id,slug:product.slug,name:product.name,category:product.category,description:product.description,price:Number(product.price),promotionalPrice:product.promotional_price===null?null:Number(product.promotional_price),wholesalePrice:product.wholesale_price===null?null:Number(product.wholesale_price),wholesaleRuleMode:product.wholesale_rule_mode,wholesaleMinimumQuantity:product.wholesale_minimum_quantity,image:product.image_url||(product.slug==='vestido-alice'?`${BASE}assets/vestido-alice.svg`:null),sizeGuideImage:product.size_guide_image_url,featured:product.featured,variants};}
function totalStock(p){return p.variants.reduce((t,v)=>t+v.sizes.reduce((s,z)=>s+z.stock,0),0)}
function retailPrice(p){return p.promotionalPrice??p.price}
function firstSelection(p){const v=p.variants.find(i=>i.sizes.some(s=>s.stock>0))??p.variants[0];if(!v)return{color:'',printPattern:'',variantId:'',size:''};const size=v.sizes.find(i=>i.stock>0)?.label??v.sizes[0]?.label??'';return{color:v.color,printPattern:v.printPattern,variantId:v.id,size}}
function launchImage(p){return p.variants.flatMap(v=>v.images??[]).find(Boolean)||p.image}
function productSlugFromPath(){const base=BASE.replace(/\/$/,'');const path=window.location.pathname.replace(base,'');const match=path.match(/^\/produto\/([^/]+)\/?$/);return match?decodeURIComponent(match[1]):''}
function productUrl(p){return `${BASE}produto/${encodeURIComponent(p.slug)}`}

export default function StoreApp(){
 const productSlug=productSlugFromPath();
 const[products,setProducts]=useState([]),[detailProduct,setDetailProduct]=useState(null),[settings,setSettings]=useState({minimumWholesaleQuantity:6,whatsapp:'556285166201'}),[storeLoading,setStoreLoading]=useState(true),[storeError,setStoreError]=useState(''),[cartOpen,setCartOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[searchTerm,setSearchTerm]=useState(''),[cart,setCart]=useState(()=>{try{return JSON.parse(localStorage.getItem('chiquehelita-cart')||'{}')}catch{return{}}}),[selections,setSelections]=useState({});
 const launchesRef=useRef(null);const[launchNavigation,setLaunchNavigation]=useState({previous:false,next:false});
 useEffect(()=>{loadStore()},[]);
 useEffect(()=>{localStorage.setItem('chiquehelita-cart',JSON.stringify(cart))},[cart]);
 async function loadStore(){setStoreLoading(true);const fields=`id, slug, name, category, description, price, promotional_price, wholesale_price, wholesale_rule_mode, wholesale_minimum_quantity, image_url, size_guide_image_url, featured, product_variants (id, color, print_pattern, image_url, active, sort_order, product_variant_stock (id, size, stock, sort_order), product_variant_images (id, image_url, sort_order, is_primary))`;const catalogQuery=supabase.from('products').select(fields).eq('active',true).order('created_at',{ascending:false});const detailQuery=productSlug?supabase.from('products').select(fields).eq('slug',productSlug).eq('active',true).limit(1):Promise.resolve({data:null,error:null});const[p,s,d]=await Promise.all([catalogQuery,supabase.from('store_settings').select('minimum_wholesale_quantity, whatsapp').limit(1).maybeSingle(),detailQuery]);if(p.error||s.error||d.error){setStoreError('Não foi possível carregar o catálogo agora.');setStoreLoading(false);return}const n=(p.data??[]).map(normalizeProduct);setProducts(n);setDetailProduct(d.data?.[0]?normalizeProduct(d.data[0]):null);setSettings({minimumWholesaleQuantity:s.data?.minimum_wholesale_quantity??6,whatsapp:s.data?.whatsapp??'556285166201'});setSelections(Object.fromEntries(n.map(x=>[x.id,firstSelection(x)])));setStoreLoading(false)}
 const cartLines=useMemo(()=>getCartLines(products,cart),[products,cart]);const cartSummary=useMemo(()=>getCartSummary(products,cart,settings.minimumWholesaleQuantity),[products,cart,settings.minimumWholesaleQuantity]);const summaryByProduct=Object.fromEntries(cartSummary.items.map(i=>[i.productId,i]));
 const normalizedSearch=searchTerm.trim().toLocaleLowerCase('pt-BR');
 const searchResults=useMemo(()=>normalizedSearch?products.filter(p=>[p.name,p.category,p.description].some(value=>String(value??'').toLocaleLowerCase('pt-BR').includes(normalizedSearch))):products,[products,normalizedSearch]);
 useEffect(()=>{if(!menuOpen&&!searchOpen)return;const closeOnEscape=(event)=>{if(event.key==='Escape'){setMenuOpen(false);setSearchOpen(false)}};document.addEventListener('keydown',closeOnEscape);return()=>document.removeEventListener('keydown',closeOnEscape)},[menuOpen,searchOpen]);
 function updateLaunchNavigation(){const row=launchesRef.current;if(!row)return;setLaunchNavigation({previous:row.scrollLeft>2,next:row.scrollLeft+row.clientWidth<row.scrollWidth-2})}
 function scrollLaunches(direction){const row=launchesRef.current;if(!row)return;row.scrollBy({left:direction*row.clientWidth,behavior:'smooth'})}
 useEffect(()=>{const row=launchesRef.current;if(!row)return;updateLaunchNavigation();const observer=new ResizeObserver(updateLaunchNavigation);observer.observe(row);window.addEventListener('resize',updateLaunchNavigation);return()=>{observer.disconnect();window.removeEventListener('resize',updateLaunchNavigation)}},[products]);
 function selectVariant(p,id){const v=p.variants.find(i=>i.id===id);if(!v)return;const cur=selections[p.id]??firstSelection(p);const same=v.sizes.find(i=>i.label===cur.size&&i.stock>0);const size=same?.label??v.sizes.find(i=>i.stock>0)?.label??v.sizes[0]?.label??'';setSelections(st=>({...st,[p.id]:{color:v.color,printPattern:v.printPattern,variantId:v.id,size}}))}
 function selectColor(p,color){const v=p.variants.find(i=>i.color===color&&i.sizes.some(s=>s.stock>0))??p.variants.find(i=>i.color===color);if(v)selectVariant(p,v.id)}
 function selectPrint(p,printPattern){const cur=selections[p.id]??firstSelection(p);const v=p.variants.find(i=>i.color===cur.color&&i.printPattern===printPattern);if(v)selectVariant(p,v.id)}
 function changeQuantity(p,v,size,delta){const key=makeCartKey(p.id,v.id,size.label);setCart(cur=>{const q=Math.max(0,Math.min(size.stock,(cur[key]??0)+delta));const next={...cur};if(q===0)delete next[key];else next[key]=q;return next})}
 function addSelected(p){const sel=selections[p.id]??firstSelection(p),v=p.variants.find(i=>i.id===sel.variantId),size=v?.sizes.find(i=>i.label===sel.size);if(!v||!size||size.stock===0)return;const key=makeCartKey(p.id,v.id,size.label);if((cart[key]??0)>=size.stock)return;changeQuantity(p,v,size,1);setCartOpen(true)}
 function ruleText(p){if(p.wholesaleRuleMode==='disabled')return'Este produto não participa das regras de atacado.';if(p.wholesaleRuleMode==='product')return`Regra específica: atacado a partir de ${p.wholesaleMinimumQuantity} unidades deste produto.`;return`Regra geral: atacado quando o carrinho atingir ${settings.minimumWholesaleQuantity} peças.`}
 const whatsappLines=cartLines.map(line=>{const s=summaryByProduct[line.product.id];return`${line.quantity}x ${line.product.name} · cor ${line.variant.color} · estampa ${line.variant.printPattern} · tam. ${line.size.label} (${s?.wholesale?'atacado':'varejo'} a ${money(s?.unitPrice??0)})`}).join(', ');
 const cartDrawer=cartOpen&&<div className="overlay" onClick={()=>setCartOpen(false)}><aside className="cart" onClick={e=>e.stopPropagation()}><div className="cart-head"><h2>Seu carrinho</h2><button className="icon" onClick={()=>setCartOpen(false)}><X/></button></div>{cartSummary.totalQuantity===0?<p className="empty">Seu carrinho está vazio.</p>:<>{cartLines.map(line=>{const s=summaryByProduct[line.product.id],image=line.variant.image||line.product.image;return <div className="cart-item" key={makeCartKey(line.product.id,line.variant.id,line.size.label)}>{image?<img src={image} alt={line.product.name}/>:<div className="cart-image-placeholder"/>}<div><strong>{line.product.name}</strong><span>Cor: {line.variant.color}</span><span>Estampa: {line.variant.printPattern}</span><span>Tamanho: {line.size.label}</span><b>{money(s?.unitPrice??0)} por peça · {s?.wholesale?'atacado':'varejo'}</b><div className="stepper"><button onClick={()=>changeQuantity(line.product,line.variant,line.size,-1)}><Minus size={15}/></button><span>{line.quantity}</span><button disabled={line.quantity>=line.size.stock} onClick={()=>changeQuantity(line.product,line.variant,line.size,1)}><Plus size={15}/></button></div></div></div>})}<div className={`wholesale-cart-status ${cartSummary.generalWholesaleActive?'active':''}`}>{cartSummary.generalWholesaleActive?`Regra geral de atacado atingida com ${cartSummary.totalQuantity} peças.`:`Faltam ${Math.max(0,settings.minimumWholesaleQuantity-cartSummary.totalQuantity)} peças para atingir a regra geral de atacado.`}</div><div className="cart-total"><span>Total do pedido · {cartSummary.totalQuantity} peças</span><strong>{money(cartSummary.total)}</strong></div><a className="button full" href={`https://wa.me/${settings.whatsapp}?text=${encodeURIComponent(`Olá! Quero fazer este pedido: ${whatsappLines}. Total de peças: ${cartSummary.totalQuantity}. Total do pedido: ${money(cartSummary.total)}.`)}`} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Finalizar pelo WhatsApp</a></>}</aside></div>;
 if(storeLoading)return <main className="empty-store"><h1>CHIQUEHELITA</h1><p>Carregando coleção...</p></main>;if(storeError)return <main className="empty-store"><h1>CHIQUEHELITA</h1><p>{storeError}</p></main>;if(productSlug&&!detailProduct)return <main className="empty-store"><h1>CHIQUEHELITA</h1><p>Produto não encontrado.</p><a className="button" href={BASE}>Voltar para a loja</a></main>;if(!products.length)return <main className="empty-store"><h1>CHIQUEHELITA</h1><p>Novidades chegando em breve.</p></main>;
 if(productSlug&&detailProduct){const p=detailProduct,sel=selections[p.id]??firstSelection(p),v=p.variants.find(i=>i.id===sel.variantId),size=v?.sizes.find(i=>i.label===sel.size),key=v&&size?makeCartKey(p.id,v.id,size.label):'';return <ProductPage product={p} selection={sel} settings={settings} cartSummary={cartSummary} cartQuantity={key?(cart[key]??0):0} onSelectVariant={id=>selectVariant(p,id)} onSelectColor={color=>selectColor(p,color)} onSelectPrint={print=>selectPrint(p,print)} onSelectSize={sizeLabel=>setSelections(cur=>({...cur,[p.id]:{...sel,size:sizeLabel}}))} onAdd={()=>addSelected(p)} onOpenCart={()=>setCartOpen(true)} cartDrawer={cartDrawer} ruleText={ruleText}/>}
 return <div className="app"><header className="header"><button className="icon mobile" aria-label={menuOpen?'Fechar menu':'Abrir menu'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(value=>!value)}>{menuOpen?<X size={22}/>:<Menu size={22}/>}</button><a className="brand-logo" href="#inicio"><img src={logo} alt="Chique Helita"/></a><nav><a href="#inicio">Início</a><a href="#novidades">Vestidos</a><a href="#promocoes">Promoções</a><a href="#sobre">Sobre nós</a></nav><div className="actions"><button className="icon" aria-label="Buscar produtos" onClick={()=>{setSearchOpen(true);setMenuOpen(false)}}><Search size={20}/></button><button className="icon cart-button" aria-label={`Abrir carrinho com ${cartSummary.totalQuantity} itens`} onClick={()=>setCartOpen(true)}><ShoppingBag size={21}/>{cartSummary.totalQuantity>0&&<span>{cartSummary.totalQuantity}</span>}</button></div></header>{menuOpen&&<nav className="mobile-menu" aria-label="Menu principal"><a href="#inicio" onClick={()=>setMenuOpen(false)}>Início</a><a href="#novidades" onClick={()=>setMenuOpen(false)}>Vestidos</a><a href="#promocoes" onClick={()=>setMenuOpen(false)}>Promoções</a><a href="#sobre" onClick={()=>setMenuOpen(false)}>Sobre nós</a></nav>}{searchOpen&&<section className="search-panel" aria-label="Busca de produtos"><div className="search-box"><Search size={20}/><input autoFocus value={searchTerm} onChange={event=>setSearchTerm(event.target.value)} placeholder="Busque por vestido, categoria ou estilo" aria-label="Termo de busca"/><button className="icon" aria-label="Fechar busca" onClick={()=>setSearchOpen(false)}><X size={21}/></button></div><div className="search-results" aria-live="polite">{normalizedSearch&&<p>{searchResults.length===1?'1 produto encontrado':`${searchResults.length} produtos encontrados`}</p>}{searchResults.length>0?<div>{searchResults.slice(0,8).map(product=><a key={product.id} href={productUrl(product)}><span className="search-result-image">{launchImage(product)?<img src={launchImage(product)} alt=""/>:<span>CH</span>}</span><span><strong>{product.name}</strong><small>{product.category} · {money(retailPrice(product))}</small></span></a>)}</div>:<div className="search-empty"><strong>Nenhum produto encontrado</strong><span>Tente buscar por outro nome ou categoria.</span></div>}</div></section>}<main>
 <section id="inicio" className="hero hero-brand"><div className="hero-copy"><p className="eyebrow">MODA FEMININA</p><h1>Elegância que<br/><em>veste você.</em></h1><p className="hero-text">Vestidos femininos escolhidos para valorizar sua beleza, com conforto e personalidade.</p><div className="hero-actions"><a className="button" href="#novidades">Ver coleção</a><a className="button secondary" href="#novidades">Comprar no atacado</a></div></div></section>
 <section className="benefits benefits-wide"><div><ShieldCheck size={22}/><strong>Compra segura</strong><span>Seu pedido protegido</span></div><div><Truck size={22}/><strong>Atendimento para todo o Brasil</strong><span>Consulte condições pelo WhatsApp</span></div><div><MessageCircle size={22}/><strong>Atendimento personalizado</strong><span>Fale diretamente com a loja</span></div><div><Sparkles size={22}/><strong>Varejo &amp; atacado</strong><span>Regras de preço aplicadas no carrinho</span></div></section>
 <section id="novidades" className="launches-section"><div className="launches-heading"><p className="eyebrow">LANÇAMENTOS</p><h2>Novidades para <em>você</em></h2><span>♥</span></div><div className="launches-carousel">{launchNavigation.previous&&<button type="button" className="launch-arrow previous" onClick={()=>scrollLaunches(-1)} aria-label="Ver produtos anteriores"><ChevronLeft/></button>}<div className="launches-row" ref={launchesRef} onScroll={updateLaunchNavigation}>{products.map((p,index)=>{const image=launchImage(p);return <a className="launch-card" key={p.id} href={productUrl(p)}><div className="launch-card-image">{image?<img src={image} alt={p.name}/>:<div className="product-placeholder">CHIQUEHELITA</div>}{index===0&&<b>Novo</b>}</div><div className="launch-card-info"><span>{p.category}</span><strong>{p.name}</strong><small>{money(retailPrice(p))}</small></div></a>})}</div>{launchNavigation.next&&<button type="button" className="launch-arrow next" onClick={()=>scrollLaunches(1)} aria-label="Ver próximos produtos"><ChevronRight/></button>}</div></section>
 <section id="promocoes" className="promo"><div><p className="eyebrow">OFERTAS ESPECIAIS</p><h2>Seu próximo look<br/><em>começa aqui.</em></h2><p>Fique de olho nas novidades e condições especiais da CHIQUEHELITA.</p><a className="button" href="#novidades">Ver produtos</a></div></section></main><footer id="sobre"><div className="footer-brand"><img src={logo} alt="Chique Helita"/><p>Moda feminina com elegância e personalidade.</p></div><div><h4>Atendimento</h4><p>Segunda a sábado</p><p>WhatsApp da loja</p></div><div><h4>Links</h4><p>Instagram</p><p>Política de privacidade</p></div></footer>
 {cartDrawer}</div>
}


